{{- $apiKey := .Values.secrets.apiKey | default (randAlphaNum 32) | b64enc  }}
{{- $mongo :=  .Values.secrets.mongoUrl | b64enc -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "api-hra-secrets") }}
{{- if $secret }}
{{- $apiKey = index $secret.data "api-key" }}
{{- $mongo = index $secret.data "mongo"}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "api-recetas.fullname" .) | printf "%s-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-recetas.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $apiKey }}
  mongo: {{ $mongo }}
