[
    {
        "PAC_PAC_Numero":"16",
        "PAC_PAC_Rut":"10771131-7",
        "PAC_PAC_ApellPater":"LAZO",
        "PAC_PAC_ApellMater":"ZAMBRA",
        "PAC_PAC_Nombre":"JACQUELINE CLOTILDE",
        "PAC_PAC_CalleHabit":"",
        "PAC_PAC_NumerHabit":"",
        "PAC_PAC_DeparHabit":" ",
        "PAC_PAC_PoblaHabit":"",
        "PAC_PAC_ComunHabit":"01",
        "PAC_PAC_CiudaHabit":"03",
        "PAC_PAC_RegioHabit":"01",
        "PAC_PAC_Fono":"",
        "PAC_PAC_TelefonoMovil":"",
        "PAC_PAC_CorreoCuerpo":""
    },
    {
        "PAC_PAC_Numero":"19",
        "PAC_PAC_Rut":"17724699-9",
        "PAC_PAC_ApellPater":"RIVERA",
        "PAC_PAC_ApellMater":"ARANCIBIA",
        "PAC_PAC_Nombre":"JOHANA GABRIEL",
        "PAC_PAC_CalleHabit":"",
        "PAC_PAC_NumerHabit":"",
        "PAC_PAC_DeparHabit":" ",
        "PAC_PAC_PoblaHabit":"",
        "PAC_PAC_ComunHabit":"01",
        "PAC_PAC_CiudaHabit":"03",
        "PAC_PAC_RegioHabit":"01",
        "PAC_PAC_Fono":"",
        "PAC_PAC_TelefonoMovil":"",
        "PAC_PAC_CorreoCuerpo":"",
        "PAC_PAC_CorreoExtension":""
    },
    {
        "PAC_PAC_Numero":"20",
        "PAC_PAC_Rut":"18502151-3",
        "PAC_PAC_ApellPater":"RIVERA",
        "PAC_PAC_ApellMater":"ARANCIBIA",
        "PAC_PAC_Nombre":"CAROLINA DEL PILAR",
        "PAC_PAC_CalleHabit":" ",
        "PAC_PAC_NumerHabit":" ",
        "PAC_PAC_DeparHabit":" ",
        "PAC_PAC_PoblaHabit":"VILLA CASPAÑA",
        "PAC_PAC_ComunHabit":"0",
        "PAC_PAC_CiudaHabit":"0",
        "PAC_PAC_RegioHabit":"01",
        "PAC_PAC_Fono":" ",
        "PAC_PAC_TelefonoMovil":" 094924483",
        "PAC_PAC_CorreoCuerpo":null,
        "PAC_PAC_CorreoExtension":null
    }
]